/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccesoriosRouteImport } from './routes/accesorios'
import { Route as AuditoriaRouteImport } from './routes/auditoria'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CajaRouteImport } from './routes/caja'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as ComprobantesRouteImport } from './routes/comprobantes'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as EscanearRouteImport } from './routes/escanear'
import { Route as GarantiasRouteImport } from './routes/garantias'
import { Route as GastosRouteImport } from './routes/gastos'
import { Route as InventarioRouteImport } from './routes/inventario'
import { Route as MetasRouteImport } from './routes/metas'
import { Route as MovimientosRouteImport } from './routes/movimientos'
import { Route as PreciosRouteImport } from './routes/precios'
import { Route as ReportesRouteImport } from './routes/reportes'
import { Route as ReservasRouteImport } from './routes/reservas'
import { Route as RevisionRouteImport } from './routes/revision'
import { Route as StockRouteImport } from './routes/stock'
import { Route as TareasRouteImport } from './routes/tareas'
import { Route as TecnicoRouteImport } from './routes/tecnico'
import { Route as VenderRouteImport } from './routes/vender'
import { Route as FinanzasCalendarioRouteImport } from './routes/finanzas/calendario'
import { Route as FinanzasGastosRouteImport } from './routes/finanzas/gastos'
import { Route as FinanzasImpuestosRouteImport } from './routes/finanzas/impuestos'
import { Route as FinanzasRemuneracionesRouteImport } from './routes/finanzas/remuneraciones'
import { Route as ApiPublicLectorAgenteDotjsRouteImport } from './routes/api/public/lector/agente[.]js'
import { Route as ApiPublicLectorEstadoRouteImport } from './routes/api/public/lector/estado'
import { Route as ApiPublicLectorInstalarDotshRouteImport } from './routes/api/public/lector/instalar[.]sh'
import { Route as ApiPublicLectorLecturaRouteImport } from './routes/api/public/lector/lectura'
import { Route as ApiPublicLectorRuntimeRouteImport } from './routes/api/public/lector/runtime'
import { Route as ApiPublicLectorVerificarRouteImport } from './routes/api/public/lector/verificar'
import { Route as ApiPublicLectorVersionRouteImport } from './routes/api/public/lector/version'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccesoriosRoute = AccesoriosRouteImport.update({
  id: '/accesorios',
  path: '/accesorios',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditoriaRoute = AuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CajaRoute = CajaRouteImport.update({
  id: '/caja',
  path: '/caja',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprobantesRoute = ComprobantesRouteImport.update({
  id: '/comprobantes',
  path: '/comprobantes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const EscanearRoute = EscanearRouteImport.update({
  id: '/escanear',
  path: '/escanear',
  getParentRoute: () => rootRouteImport,
} as any)
const GarantiasRoute = GarantiasRouteImport.update({
  id: '/garantias',
  path: '/garantias',
  getParentRoute: () => rootRouteImport,
} as any)
const GastosRoute = GastosRouteImport.update({
  id: '/gastos',
  path: '/gastos',
  getParentRoute: () => rootRouteImport,
} as any)
const InventarioRoute = InventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => rootRouteImport,
} as any)
const MetasRoute = MetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => rootRouteImport,
} as any)
const MovimientosRoute = MovimientosRouteImport.update({
  id: '/movimientos',
  path: '/movimientos',
  getParentRoute: () => rootRouteImport,
} as any)
const PreciosRoute = PreciosRouteImport.update({
  id: '/precios',
  path: '/precios',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportesRoute = ReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservasRoute = ReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => rootRouteImport,
} as any)
const RevisionRoute = RevisionRouteImport.update({
  id: '/revision',
  path: '/revision',
  getParentRoute: () => rootRouteImport,
} as any)
const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const TareasRoute = TareasRouteImport.update({
  id: '/tareas',
  path: '/tareas',
  getParentRoute: () => rootRouteImport,
} as any)
const TecnicoRoute = TecnicoRouteImport.update({
  id: '/tecnico',
  path: '/tecnico',
  getParentRoute: () => rootRouteImport,
} as any)
const VenderRoute = VenderRouteImport.update({
  id: '/vender',
  path: '/vender',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanzasCalendarioRoute = FinanzasCalendarioRouteImport.update({
  id: '/finanzas/calendario',
  path: '/finanzas/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanzasGastosRoute = FinanzasGastosRouteImport.update({
  id: '/finanzas/gastos',
  path: '/finanzas/gastos',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanzasImpuestosRoute = FinanzasImpuestosRouteImport.update({
  id: '/finanzas/impuestos',
  path: '/finanzas/impuestos',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanzasRemuneracionesRoute = FinanzasRemuneracionesRouteImport.update({
  id: '/finanzas/remuneraciones',
  path: '/finanzas/remuneraciones',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLectorAgenteDotjsRoute =
  ApiPublicLectorAgenteDotjsRouteImport.update({
    id: '/api/public/lector/agente.js',
    path: '/api/public/lector/agente.js',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLectorEstadoRoute = ApiPublicLectorEstadoRouteImport.update({
  id: '/api/public/lector/estado',
  path: '/api/public/lector/estado',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLectorInstalarDotshRoute =
  ApiPublicLectorInstalarDotshRouteImport.update({
    id: '/api/public/lector/instalar.sh',
    path: '/api/public/lector/instalar.sh',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLectorLecturaRoute = ApiPublicLectorLecturaRouteImport.update({
  id: '/api/public/lector/lectura',
  path: '/api/public/lector/lectura',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLectorRuntimeRoute = ApiPublicLectorRuntimeRouteImport.update({
  id: '/api/public/lector/runtime',
  path: '/api/public/lector/runtime',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLectorVerificarRoute =
  ApiPublicLectorVerificarRouteImport.update({
    id: '/api/public/lector/verificar',
    path: '/api/public/lector/verificar',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLectorVersionRoute = ApiPublicLectorVersionRouteImport.update({
  id: '/api/public/lector/version',
  path: '/api/public/lector/version',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accesorios': typeof AccesoriosRoute
  '/auditoria': typeof AuditoriaRoute
  '/auth': typeof AuthRoute
  '/caja': typeof CajaRoute
  '/clientes': typeof ClientesRoute
  '/comprobantes': typeof ComprobantesRoute
  '/configuracion': typeof ConfiguracionRoute
  '/escanear': typeof EscanearRoute
  '/garantias': typeof GarantiasRoute
  '/gastos': typeof GastosRoute
  '/inventario': typeof InventarioRoute
  '/metas': typeof MetasRoute
  '/movimientos': typeof MovimientosRoute
  '/precios': typeof PreciosRoute
  '/reportes': typeof ReportesRoute
  '/reservas': typeof ReservasRoute
  '/revision': typeof RevisionRoute
  '/stock': typeof StockRoute
  '/tareas': typeof TareasRoute
  '/tecnico': typeof TecnicoRoute
  '/vender': typeof VenderRoute
  '/finanzas/calendario': typeof FinanzasCalendarioRoute
  '/finanzas/gastos': typeof FinanzasGastosRoute
  '/finanzas/impuestos': typeof FinanzasImpuestosRoute
  '/finanzas/remuneraciones': typeof FinanzasRemuneracionesRoute
  '/api/public/lector/agente.js': typeof ApiPublicLectorAgenteDotjsRoute
  '/api/public/lector/estado': typeof ApiPublicLectorEstadoRoute
  '/api/public/lector/instalar.sh': typeof ApiPublicLectorInstalarDotshRoute
  '/api/public/lector/lectura': typeof ApiPublicLectorLecturaRoute
  '/api/public/lector/runtime': typeof ApiPublicLectorRuntimeRoute
  '/api/public/lector/verificar': typeof ApiPublicLectorVerificarRoute
  '/api/public/lector/version': typeof ApiPublicLectorVersionRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accesorios': typeof AccesoriosRoute
  '/auditoria': typeof AuditoriaRoute
  '/auth': typeof AuthRoute
  '/caja': typeof CajaRoute
  '/clientes': typeof ClientesRoute
  '/comprobantes': typeof ComprobantesRoute
  '/configuracion': typeof ConfiguracionRoute
  '/escanear': typeof EscanearRoute
  '/garantias': typeof GarantiasRoute
  '/gastos': typeof GastosRoute
  '/inventario': typeof InventarioRoute
  '/metas': typeof MetasRoute
  '/movimientos': typeof MovimientosRoute
  '/precios': typeof PreciosRoute
  '/reportes': typeof ReportesRoute
  '/reservas': typeof ReservasRoute
  '/revision': typeof RevisionRoute
  '/stock': typeof StockRoute
  '/tareas': typeof TareasRoute
  '/tecnico': typeof TecnicoRoute
  '/vender': typeof VenderRoute
  '/finanzas/calendario': typeof FinanzasCalendarioRoute
  '/finanzas/gastos': typeof FinanzasGastosRoute
  '/finanzas/impuestos': typeof FinanzasImpuestosRoute
  '/finanzas/remuneraciones': typeof FinanzasRemuneracionesRoute
  '/api/public/lector/agente.js': typeof ApiPublicLectorAgenteDotjsRoute
  '/api/public/lector/estado': typeof ApiPublicLectorEstadoRoute
  '/api/public/lector/instalar.sh': typeof ApiPublicLectorInstalarDotshRoute
  '/api/public/lector/lectura': typeof ApiPublicLectorLecturaRoute
  '/api/public/lector/runtime': typeof ApiPublicLectorRuntimeRoute
  '/api/public/lector/verificar': typeof ApiPublicLectorVerificarRoute
  '/api/public/lector/version': typeof ApiPublicLectorVersionRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accesorios': typeof AccesoriosRoute
  '/auditoria': typeof AuditoriaRoute
  '/auth': typeof AuthRoute
  '/caja': typeof CajaRoute
  '/clientes': typeof ClientesRoute
  '/comprobantes': typeof ComprobantesRoute
  '/configuracion': typeof ConfiguracionRoute
  '/escanear': typeof EscanearRoute
  '/garantias': typeof GarantiasRoute
  '/gastos': typeof GastosRoute
  '/inventario': typeof InventarioRoute
  '/metas': typeof MetasRoute
  '/movimientos': typeof MovimientosRoute
  '/precios': typeof PreciosRoute
  '/reportes': typeof ReportesRoute
  '/reservas': typeof ReservasRoute
  '/revision': typeof RevisionRoute
  '/stock': typeof StockRoute
  '/tareas': typeof TareasRoute
  '/tecnico': typeof TecnicoRoute
  '/vender': typeof VenderRoute
  '/finanzas/calendario': typeof FinanzasCalendarioRoute
  '/finanzas/gastos': typeof FinanzasGastosRoute
  '/finanzas/impuestos': typeof FinanzasImpuestosRoute
  '/finanzas/remuneraciones': typeof FinanzasRemuneracionesRoute
  '/api/public/lector/agente.js': typeof ApiPublicLectorAgenteDotjsRoute
  '/api/public/lector/estado': typeof ApiPublicLectorEstadoRoute
  '/api/public/lector/instalar.sh': typeof ApiPublicLectorInstalarDotshRoute
  '/api/public/lector/lectura': typeof ApiPublicLectorLecturaRoute
  '/api/public/lector/runtime': typeof ApiPublicLectorRuntimeRoute
  '/api/public/lector/verificar': typeof ApiPublicLectorVerificarRoute
  '/api/public/lector/version': typeof ApiPublicLectorVersionRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accesorios'
    | '/auditoria'
    | '/auth'
    | '/caja'
    | '/clientes'
    | '/comprobantes'
    | '/configuracion'
    | '/escanear'
    | '/garantias'
    | '/gastos'
    | '/inventario'
    | '/metas'
    | '/movimientos'
    | '/precios'
    | '/reportes'
    | '/reservas'
    | '/revision'
    | '/stock'
    | '/tareas'
    | '/tecnico'
    | '/vender'
    | '/finanzas/calendario'
    | '/finanzas/gastos'
    | '/finanzas/impuestos'
    | '/finanzas/remuneraciones'
    | '/api/public/lector/agente.js'
    | '/api/public/lector/estado'
    | '/api/public/lector/instalar.sh'
    | '/api/public/lector/lectura'
    | '/api/public/lector/runtime'
    | '/api/public/lector/verificar'
    | '/api/public/lector/version'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accesorios'
    | '/auditoria'
    | '/auth'
    | '/caja'
    | '/clientes'
    | '/comprobantes'
    | '/configuracion'
    | '/escanear'
    | '/garantias'
    | '/gastos'
    | '/inventario'
    | '/metas'
    | '/movimientos'
    | '/precios'
    | '/reportes'
    | '/reservas'
    | '/revision'
    | '/stock'
    | '/tareas'
    | '/tecnico'
    | '/vender'
    | '/finanzas/calendario'
    | '/finanzas/gastos'
    | '/finanzas/impuestos'
    | '/finanzas/remuneraciones'
    | '/api/public/lector/agente.js'
    | '/api/public/lector/estado'
    | '/api/public/lector/instalar.sh'
    | '/api/public/lector/lectura'
    | '/api/public/lector/runtime'
    | '/api/public/lector/verificar'
    | '/api/public/lector/version'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/accesorios'
    | '/auditoria'
    | '/auth'
    | '/caja'
    | '/clientes'
    | '/comprobantes'
    | '/configuracion'
    | '/escanear'
    | '/garantias'
    | '/gastos'
    | '/inventario'
    | '/metas'
    | '/movimientos'
    | '/precios'
    | '/reportes'
    | '/reservas'
    | '/revision'
    | '/stock'
    | '/tareas'
    | '/tecnico'
    | '/vender'
    | '/finanzas/calendario'
    | '/finanzas/gastos'
    | '/finanzas/impuestos'
    | '/finanzas/remuneraciones'
    | '/api/public/lector/agente.js'
    | '/api/public/lector/estado'
    | '/api/public/lector/instalar.sh'
    | '/api/public/lector/lectura'
    | '/api/public/lector/runtime'
    | '/api/public/lector/verificar'
    | '/api/public/lector/version'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccesoriosRoute: typeof AccesoriosRoute
  AuditoriaRoute: typeof AuditoriaRoute
  AuthRoute: typeof AuthRoute
  CajaRoute: typeof CajaRoute
  ClientesRoute: typeof ClientesRoute
  ComprobantesRoute: typeof ComprobantesRoute
  ConfiguracionRoute: typeof ConfiguracionRoute
  EscanearRoute: typeof EscanearRoute
  GarantiasRoute: typeof GarantiasRoute
  GastosRoute: typeof GastosRoute
  InventarioRoute: typeof InventarioRoute
  MetasRoute: typeof MetasRoute
  MovimientosRoute: typeof MovimientosRoute
  PreciosRoute: typeof PreciosRoute
  ReportesRoute: typeof ReportesRoute
  ReservasRoute: typeof ReservasRoute
  RevisionRoute: typeof RevisionRoute
  StockRoute: typeof StockRoute
  TareasRoute: typeof TareasRoute
  TecnicoRoute: typeof TecnicoRoute
  VenderRoute: typeof VenderRoute
  FinanzasCalendarioRoute: typeof FinanzasCalendarioRoute
  FinanzasGastosRoute: typeof FinanzasGastosRoute
  FinanzasImpuestosRoute: typeof FinanzasImpuestosRoute
  FinanzasRemuneracionesRoute: typeof FinanzasRemuneracionesRoute
  ApiPublicLectorAgenteDotjsRoute: typeof ApiPublicLectorAgenteDotjsRoute
  ApiPublicLectorEstadoRoute: typeof ApiPublicLectorEstadoRoute
  ApiPublicLectorInstalarDotshRoute: typeof ApiPublicLectorInstalarDotshRoute
  ApiPublicLectorLecturaRoute: typeof ApiPublicLectorLecturaRoute
  ApiPublicLectorRuntimeRoute: typeof ApiPublicLectorRuntimeRoute
  ApiPublicLectorVerificarRoute: typeof ApiPublicLectorVerificarRoute
  ApiPublicLectorVersionRoute: typeof ApiPublicLectorVersionRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accesorios': {
      id: '/accesorios'
      path: '/accesorios'
      fullPath: '/accesorios'
      preLoaderRoute: typeof AccesoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditoria': {
      id: '/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caja': {
      id: '/caja'
      path: '/caja'
      fullPath: '/caja'
      preLoaderRoute: typeof CajaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comprobantes': {
      id: '/comprobantes'
      path: '/comprobantes'
      fullPath: '/comprobantes'
      preLoaderRoute: typeof ComprobantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escanear': {
      id: '/escanear'
      path: '/escanear'
      fullPath: '/escanear'
      preLoaderRoute: typeof EscanearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garantias': {
      id: '/garantias'
      path: '/garantias'
      fullPath: '/garantias'
      preLoaderRoute: typeof GarantiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gastos': {
      id: '/gastos'
      path: '/gastos'
      fullPath: '/gastos'
      preLoaderRoute: typeof GastosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventario': {
      id: '/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof InventarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metas': {
      id: '/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof MetasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movimientos': {
      id: '/movimientos'
      path: '/movimientos'
      fullPath: '/movimientos'
      preLoaderRoute: typeof MovimientosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precios': {
      id: '/precios'
      path: '/precios'
      fullPath: '/precios'
      preLoaderRoute: typeof PreciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportes': {
      id: '/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof ReportesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservas': {
      id: '/reservas'
      path: '/reservas'
      fullPath: '/reservas'
      preLoaderRoute: typeof ReservasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revision': {
      id: '/revision'
      path: '/revision'
      fullPath: '/revision'
      preLoaderRoute: typeof RevisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tareas': {
      id: '/tareas'
      path: '/tareas'
      fullPath: '/tareas'
      preLoaderRoute: typeof TareasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tecnico': {
      id: '/tecnico'
      path: '/tecnico'
      fullPath: '/tecnico'
      preLoaderRoute: typeof TecnicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vender': {
      id: '/vender'
      path: '/vender'
      fullPath: '/vender'
      preLoaderRoute: typeof VenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finanzas/calendario': {
      id: '/finanzas/calendario'
      path: '/finanzas/calendario'
      fullPath: '/finanzas/calendario'
      preLoaderRoute: typeof FinanzasCalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finanzas/gastos': {
      id: '/finanzas/gastos'
      path: '/finanzas/gastos'
      fullPath: '/finanzas/gastos'
      preLoaderRoute: typeof FinanzasGastosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finanzas/impuestos': {
      id: '/finanzas/impuestos'
      path: '/finanzas/impuestos'
      fullPath: '/finanzas/impuestos'
      preLoaderRoute: typeof FinanzasImpuestosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finanzas/remuneraciones': {
      id: '/finanzas/remuneraciones'
      path: '/finanzas/remuneraciones'
      fullPath: '/finanzas/remuneraciones'
      preLoaderRoute: typeof FinanzasRemuneracionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/lector/agente.js': {
      id: '/api/public/lector/agente.js'
      path: '/api/public/lector/agente.js'
      fullPath: '/api/public/lector/agente.js'
      preLoaderRoute: typeof ApiPublicLectorAgenteDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/lector/estado': {
      id: '/api/public/lector/estado'
      path: '/api/public/lector/estado'
      fullPath: '/api/public/lector/estado'
      preLoaderRoute: typeof ApiPublicLectorEstadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/lector/instalar.sh': {
      id: '/api/public/lector/instalar.sh'
      path: '/api/public/lector/instalar.sh'
      fullPath: '/api/public/lector/instalar.sh'
      preLoaderRoute: typeof ApiPublicLectorInstalarDotshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/lector/lectura': {
      id: '/api/public/lector/lectura'
      path: '/api/public/lector/lectura'
      fullPath: '/api/public/lector/lectura'
      preLoaderRoute: typeof ApiPublicLectorLecturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/lector/runtime': {
      id: '/api/public/lector/runtime'
      path: '/api/public/lector/runtime'
      fullPath: '/api/public/lector/runtime'
      preLoaderRoute: typeof ApiPublicLectorRuntimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/lector/verificar': {
      id: '/api/public/lector/verificar'
      path: '/api/public/lector/verificar'
      fullPath: '/api/public/lector/verificar'
      preLoaderRoute: typeof ApiPublicLectorVerificarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/lector/version': {
      id: '/api/public/lector/version'
      path: '/api/public/lector/version'
      fullPath: '/api/public/lector/version'
      preLoaderRoute: typeof ApiPublicLectorVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccesoriosRoute: AccesoriosRoute,
  AuditoriaRoute: AuditoriaRoute,
  AuthRoute: AuthRoute,
  CajaRoute: CajaRoute,
  ClientesRoute: ClientesRoute,
  ComprobantesRoute: ComprobantesRoute,
  ConfiguracionRoute: ConfiguracionRoute,
  EscanearRoute: EscanearRoute,
  GarantiasRoute: GarantiasRoute,
  GastosRoute: GastosRoute,
  InventarioRoute: InventarioRoute,
  MetasRoute: MetasRoute,
  MovimientosRoute: MovimientosRoute,
  PreciosRoute: PreciosRoute,
  ReportesRoute: ReportesRoute,
  ReservasRoute: ReservasRoute,
  RevisionRoute: RevisionRoute,
  StockRoute: StockRoute,
  TareasRoute: TareasRoute,
  TecnicoRoute: TecnicoRoute,
  VenderRoute: VenderRoute,
  FinanzasCalendarioRoute: FinanzasCalendarioRoute,
  FinanzasGastosRoute: FinanzasGastosRoute,
  FinanzasImpuestosRoute: FinanzasImpuestosRoute,
  FinanzasRemuneracionesRoute: FinanzasRemuneracionesRoute,
  ApiPublicLectorAgenteDotjsRoute: ApiPublicLectorAgenteDotjsRoute,
  ApiPublicLectorEstadoRoute: ApiPublicLectorEstadoRoute,
  ApiPublicLectorInstalarDotshRoute: ApiPublicLectorInstalarDotshRoute,
  ApiPublicLectorLecturaRoute: ApiPublicLectorLecturaRoute,
  ApiPublicLectorRuntimeRoute: ApiPublicLectorRuntimeRoute,
  ApiPublicLectorVerificarRoute: ApiPublicLectorVerificarRoute,
  ApiPublicLectorVersionRoute: ApiPublicLectorVersionRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
